### ISSUE TITLE
make kind name "KubeTriggerConfig" to be "TriggerService"

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kube-trigger#2]
Let's refactor the schema to be:

```
triggers:
  -   k8s-resource-watcher:
       apiVersion: v1
       kind: ConfigMap
       namespace: default
       # Only watch update event.
       events:
         - update
    filters:
      # Filter the events above.
      - cue-validator:
          template: |
            metadata: name: =~"this-will-trigger-update-.*"
    actions:
      - bump-application-revision:
          namespace: default
          labelSelectors:
            my-label: my-value
```

It can be more convenient as trigger config.
